services:
  api:
    build:
      context: . 
      dockerfile: TicTacToe.Api/Dockerfile
    container_name: tictactoe-api
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=tictactoe_db;User Id=postgres;Password=postgres;
    depends_on:
      db:
        condition: service_healthy 
        
  db:
    image: postgres:latest 
    container_name: tictactoe-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=tictactoe_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tictactoe_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: